site_name: Docs for AnotherAURHelper
theme:
    name: mkdocs
    color_mode: dark
    user_color_mode_toggle: true
markdown_extensions:
  - admonition
  - codehilite
nav:
  - Home: index.md
  - Setup with LXC: setup_lxc.md
